<?php require_once 'templates/layout/header.phtml'; ?>

<?php if ($this->user && $this->user->rol == 'admin'): ?>
    <div class="d-flex justify-content-center">
        <div class="col-lg-4">
        <h2 class="text-center mb-4 p-3">Actualizar categoría</h2>
        <form action="<?= BASE_URL . 'categorias/actualizar/' . $categoria->id_categoria ?>" method="post" class="p-4 shadow rounded bg-light">
                <div class="mb-3">
                    <label for="nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresa el nombre" value="<?= $categoria->nombre ?>" required>
                </div>
                <div class="mb-3">
                    <label for="descripcion" class="form-label">Descripción</label>
                    <textarea class="form-control" id="descripcion" name="descripcion" rows="3" placeholder="Ingresa una descripción" required><?= $categoria->descripcion; ?></textarea>
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary btn-lg">Actualizar</button>
                </div>  
            </form>
        </div>
    </div>
<?php endif; ?>

<?php require_once 'templates/layout/footer.phtml'; ?>
