<?php require 'templates/layout/header.phtml' ?>

<div class="container mt-5">
    <h1 class="text-center mb-4">Iniciar Sesión</h1>

    <?php if ($error): ?>
        <div class='alert alert-danger' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>

    <form method='POST' action='login'>
        <div class='form-group mb-3'>
            <label for='user'>Usuario</label>
            <input type='text' class='form-control' id='user' name='user' required />
        </div>
        <div class='form-group mb-3'>
            <label for='password'>Contraseña</label>
            <input type='password' class='form-control' id='password' name='password' required />
        </div>
        <button type='submit' class='btn btn-primary w-100'>Iniciar Sesión</button>
    </form>
</div>

<?php require 'templates/layout/footer.phtml' ?>

<?php