<?php require 'templates/layout/header.phtml' ?>

<div class="container mt-5 bg-light p-4">
    <h1 class="text-center mb-4 fs-2">Detalles del Producto</h1>
    <div class="card shadow-sm border-0">
        <div class="card-body">
            <h2 class="card-title fs-3 text-primary mb-3"><?= htmlspecialchars($product->nombre); ?></h2>
            <p class="card-text text-muted fs-6"><strong>Descripción:</strong> <?= htmlspecialchars($product->descripcion); ?></p>
            <p class="card-text text-muted fs-6"><strong>Precio:</strong> $<?= htmlspecialchars($product->precio); ?></p>
            <p class="card-text text-muted fs-6"><strong>Peso Neto:</strong> <?= htmlspecialchars($product->peso_neto); ?> kg</p>
            <p class="card-text text-muted fs-6"><strong>Fecha de Empaquetado:</strong> <?= htmlspecialchars($product->fecha_empaquetado); ?></p>
            <p class="card-text text-muted fs-6"><strong>Fecha de Vencimiento:</strong> <?= htmlspecialchars($product->fecha_vencimiento); ?></p>
            <p class="card-text text-muted fs-6"><strong>Stock Disponible:</strong> <?= htmlspecialchars($product->stock); ?></p>
            <a href="./productos" class="btn btn-outline-primary mt-3">Volver al Listado</a>
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml' ?>