<!-- Formulario para agregar una categoría -->
<div class="container mt-5">
    <div class="card shadow-sm border-0">
        <div class="card-body">
            <h2 class="card-title mb-4">Agregar Categoría</h2>
            <form action="categorias" method="post">
                <div class="mb-3">
                    <label for="nombreAgregar" class="form-label">Nombre de la categoría</label>
                    <input type="text" name="nombre" id="nombreAgregar" class="form-control" required />
                </div>
                <div class="mb-3">
                    <label for="descripcionAgregar" class="form-label">Descripción</label>
                    <input type="text" name="descripcion" id="descripcionAgregar" class="form-control" required />
                </div>
                <button type="submit" class="btn btn-success w-100">Agregar</button>
            </form>
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="card shadow-sm border-0">
        <div class="card-body">
            <h2 class="card-title mb-4">Actualizar Categoría</h2>
            <form action="editar/<?php echo $categorias[0]->id; ?>" method="post" id="formCategoria">
                <div class="mb-3">
                    <label for="categoria" class="form-label">Seleccionar Categoría</label>
                    <select name="categoria" id="categoria" class="form-select" onchange="document.getElementById('formCategoria').action = 'editar/' + this.value;">
                        <?php foreach ($categorias as $categoria) : ?>
                            <option value="<?php echo $categoria->id; ?>">
                                <?php echo $categoria->nombre; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label">Nuevo nombre</label>
                    <input type="text" name="nombre" id="nombre" class="form-control" required />
                </div>
                <div class="mb-3">
                    <label for="descripcion" class="form-label">Nueva descripción</label>
                    <input type="text" name="descripcion" id="descripcion" class="form-control" required />
                </div>
                <button type="submit" class="btn btn-primary w-100">Actualizar</button>
            </form>
        </div>
    </div>
</div>
