<footer class="bg-dark text-white text-center py-4 mt-5">
    <div class="container">
        <p class="mb-1">&copy; 2024 Sitio web hecho por Nahuel Lamorte y Mateo Alonso</p>
        <p class="mb-0">
            <a href="#" class="text-white me-3">Política de Privacidad</a>
            <a href="#" class="text-white me-3">Términos de Servicio</a>
            <a href="#" class="text-white">Contacto</a>
        </p>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>
